language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake ninja-build

script:
  - cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
  - cmake --build build
  - ctest --test-dir build/tests --output-on-failure
