#ifndef __FALCON_HTTP__
#define __FALCON_HTTP__

typedef enum
{
  /* 1xx: Informational */
  FC_STATUS_CONTINUE = 100,
  FC_STATUS_SWITCHING_PROTOCOLS = 101,
  FC_STATUS_PROCESSING = 102,
  FC_STATUS_EARLY_HINTS = 103,

  /* 2xx: Success */
  FC_STATUS_OK = 200,
  FC_STATUS_CREATED = 201,
  FC_STATUS_ACCEPTED = 202,
  FC_STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
  FC_STATUS_NO_CONTENT = 204,
  FC_STATUS_RESET_CONTENT = 205,
  FC_STATUS_PARTIAL_CONTENT = 206,
  FC_STATUS_MULTI_STATUS = 207,
  FC_STATUS_ALREADY_REPORTED = 208,
  FC_STATUS_IM_USED = 226,

  /* 3xx: Redirection */
  FC_STATUS_MULTIPLE_CHOICES = 300,
  FC_STATUS_MOVED_PERMANENTLY = 301,
  FC_STATUS_FOUND = 302,
  FC_STATUS_SEE_OTHER = 303,
  FC_STATUS_NOT_MODIFIED = 304,
  FC_STATUS_USE_PROXY = 305,
  FC_STATUS_SWITCH_PROXY = 306,
  FC_STATUS_TEMPORARY_REDIRECT = 307,
  FC_STATUS_PERMANENT_REDIRECT = 308,

  /* 4xx: Client Errors */
  FC_STATUS_BAD_REQUEST = 400,
  FC_STATUS_UNAUTHORIZED = 401,
  FC_STATUS_PAYMENT_REQUIRED = 402,
  FC_STATUS_FORBIDDEN = 403,
  FC_STATUS_NOT_FOUND = 404,
  FC_STATUS_METHOD_NOT_ALLOWED = 405,
  FC_STATUS_NOT_ACCEPTABLE = 406,
  FC_STATUS_PROXY_AUTH_REQUIRED = 407,
  FC_STATUS_REQUEST_TIMEOUT = 408,
  FC_STATUS_CONFLICT = 409,
  FC_STATUS_GONE = 410,
  FC_STATUS_LENGTH_REQUIRED = 411,
  FC_STATUS_PRECONDITION_FAILED = 412,
  FC_STATUS_PAYLOAD_TOO_LARGE = 413,
  FC_STATUS_URI_TOO_LONG = 414,
  FC_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
  FC_STATUS_RANGE_NOT_SATISFIABLE = 416,
  FC_STATUS_EXPECTATION_FAILED = 417,
  FC_STATUS_IM_A_TEAPOT = 418, // Fun Easter Egg status code
  FC_STATUS_MISDIRECTED_REQUEST = 421,
  FC_STATUS_UNPROCESSABLE_ENTITY = 422,
  FC_STATUS_LOCKED = 423,
  FC_STATUS_FAILED_DEPENDENCY = 424,
  FC_STATUS_TOO_EARLY = 425,
  FC_STATUS_UPGRADE_REQUIRED = 426,
  FC_STATUS_PRECONDITION_REQUIRED = 428,
  FC_STATUS_TOO_MANY_REQUESTS = 429,
  FC_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  FC_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,

  /* 5xx: Server Errors */
  FC_STATUS_INTERNAL_SERVER_ERROR = 500,
  FC_STATUS_NOT_IMPLEMENTED = 501,
  FC_STATUS_BAD_GATEWAY = 502,
  FC_STATUS_SERVICE_UNAVAILABLE = 503,
  FC_STATUS_GATEWAY_TIMEOUT = 504,
  FC_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
  FC_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
  FC_STATUS_INSUFFICIENT_STORAGE = 507,
  FC_STATUS_LOOP_DETECTED = 508,
  FC_STATUS_NOT_EXTENDED = 510,
  FC_STATUS_NETWORK_AUTH_REQUIRED = 511
} fc_http_status;

typedef enum
{
  FC_HTTP_GET,
  FC_HTTP_POST,
  FC_HTTP_PUT,
  FC_HTTP_DELETE,
  FC_HTTP_HEAD,
  FC_HTTP_OPTIONS,
  FC_HTTP_TRACE,
  FC_HTTP_CONNECT,
  FC_HTTP_PATCH,

  /* Must be the last one */
  FC__HTTP_METHODS_COUNT
} fc_http_method;

char *fc__http_status_str(fc_http_status status);
char *fc__http_method_str(fc_http_method method);

#endif // !__FALCON_HTTP__
